### ISSUE TITLE
Return null

### ISSUE THREAD

**Issue by NekoKamiDesu** [mrkno/Kassy#125]
slap returns null when used in group chats (possibly because of sender name)
returns msg as "!slap <person> fucked up. Damn you null."

**Comment by mrkno** [comment]
Please see and track this in the other issue you filed. https://github.com/mrkno/Kassy/issues/124

**Comment by ParasDPain** [comment]
Regarding the null pointer caused in the `slap` module. I did a [test on jsfiddle](http://jsfiddle.net/parasdpain/ta7yph1e/) and it is running as expected.

@NekoKamiDesu It would be helpful if you can run Kassy in debug mode and post the appropriate message. It will log a critical message as specified at line 79 in `Kassy/core/platform.js`

**Comment by mrkno** [comment]
If you are using facebook, please check if https://github.com/mrkno/Kassy/commit/c9ac47ddb5d6846de19902d1f36c1914c21d3bcf fixed your issue

(`git pull && npm update`)

**Comment by NekoKamiDesu** [comment]
@ParasDPain 
Here seems to be the issue;
`TypeError: Cannot read property 'trim' of undefined
    at Object.exports.run (slap.js:51:31)
    at Platform.handleTransaction (platform.js:41:28)
    at Platform.messageRxd (platform.js:75:22)
    at facebook.js:90:6
    at parsePackets (C:\Users\Koret\Desktop\IzumiBot\node_modules\facebook-chat-api\src\listen.js:161:22)
    at Array.forEach (native)
    at C:\Users\Koret\Desktop\IzumiBot\node_modules\facebook-chat-api\src\listen.js:108:12
    at tryCatcher (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Koret\Desktop\IzumiBot\node_modules\bluebird\js\main\async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`

@mrkno 
The api update didn't fix the problem :)

**Comment by mrkno** [comment]
@NekoKamiDesu It appears the upstream API we are depending on https://github.com/Schmavery/facebook-chat-api, no longer provides the `senderName` attribute as a part of their `message` object https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apilistencallback.

**Comment by mrkno** [comment]
https://github.com/mrkno/Kassy/pull/132 should in all cases but [the bug which I don't think lies with us](https://github.com/Schmavery/facebook-chat-api/issues/260) fix this problem on facebook (`sender_name` should no longer be `null` on every message from facebook).

@ParasDPain if you are interested, you are welcome to be the reviewer on the PR.

**Comment by ParasDPain** [comment]
Great work! I'll have a look

**Comment by NekoKamiDesu** [comment]
Cool! Hope #132 will work according to plan!
